### ISSUE TITLE
RunTAP to evaluate Mag_now rather than baseline_mag as a selection threshold

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#116]

**Comment by rachel3834** [comment]
We may be being overly conservative in selecting events with bright baseline magnitudes rather than Mag_now>17.5mag.  Let's review this threshold and consider whether it needs to be updated.

**Comment by KKruszynska** [comment]
PR #119 is fixing this issue, the magnitude selection for long events was changed to mag_now>17.5mag. This should promote more events.

**Comment by rachel3834** [comment]
PR merged and deployed - thanks!
