### ISSUE TITLE
Broken logic in classyfing Gaia targets

### ISSUE THREAD

**Issue by KKruszynska** [LCOGT/mop#125]
I noticed that gaia_classifier didn't classify https://mop.lco.global/targets/39231/?c=5973 this target as a QSO. It is a known QSO, listed in the Miliquas catalogue. If the classifier worked as intended, this should be recorded in MOP as a quasar. Lack of the expected behaviour is caused by the broken logic in the classifier.

**Comment by KKruszynska** [comment]
Partially fixed by pull request #126.

Now the events that are QSOs are marked as is_QSO=True, but depending on the quality of the fit, might be classified as "Unclassified variable/Unclassified", "Unclassified poor fit / Microlensing stellar/planet" or "Unclassified poor fit / Microlensing long-tE".

**Comment by rachel3834** [comment]
This has been revised as a result of Issue #141
