### ISSUE TITLE
Server 500 Error when submitting observing request via MOP

### ISSUE THREAD

**Issue by ytsapras** [LCOGT/mop#129]
The submitted parameters were as follows:

Name*
 gaia21ccu_baseline
Proposal*
 Characterizing the Milky Way’s Hidden Population (SOAR2024A-009)
Observation mode*
 Normal
Intra Proposal Priority (IPP factor)*
 1.05
Optimization type
 Time
Configuration Repeats
 1
Start*
 08/02/2024
End*
 16/02/2024

Instrument Type
 1.0 meter Sinistro
Configuration Type
 Exposure

Exposure Time
 160
Exposure Count
 2
Filter
 SDSS-gp

Max Airmass
 1.6
Minimum Lunar Distance
 30
Maximum Lunar Phase
 0.9

Period 24
Jitter 12

(Similarly for SDSS-ip (Configuration 2) but with ExpTime set to 80 (in instrument configuration 2) )

**Comment by KKruszynska** [comment]
Yiannis, you chose the wrong proposal id. "Characterizing the Milky Way’s Hidden Population (SOAR2024A-009)" is the SOAR proposal, OMEGA-II Key Project is "Characterizing the Milky Way’s Hidden Population (KEY2023B-004)". MOP will give you server 500 error if something in the configuration of the request is wrong.

**Comment by ytsapras** [comment]
Ah, sorry, my bad. That explains it!

**Comment by ytsapras** [comment]
Ah, sorry, my bad. That explains it! I only looked at the text, not the identifier.
