### ISSUE TITLE
Highlighting observed targets in Priority Targets View 

### ISSUE THREAD

**Issue by KKruszynska** [LCOGT/mop#155]
We realized with Markus, that it would be convenient to highlight targets that are followed-up in the Priority View.

**Comment by mpgh** [comment]
As part of the update, one could consider showing also the remaining hours of 1m time, as well as the available time per 24h until the end of the KP.

**Comment by mpgh** [comment]
The list of priority events could also come with a table entry how many hours are likely to be requested, perhaps also per night.

**Comment by KKruszynska** [comment]
For reference, I post the RoboNET priority targets view I got from Markus.
![image (1)](https://github.com/LCOGT/mop/assets/36246703/e8ac5587-7f74-4e0e-8fc6-5d447f404610)

**Comment by KKruszynska** [comment]
@mpgh I created a similar thing in my local MOP. Could you have a look and give me some feedback if this looks fine?
Targets that have names underlined and in bold are observed, targets that are 5 days before peak have a row background in blue.
![image](https://github.com/LCOGT/mop/assets/36246703/1f922391-590a-4ef7-80d6-80823a6865fe)

**Comment by mpgh** [comment]
Thanks so much. I find this very helpful, since it saves the extra check if sth. is observed. Well done!

**Comment by mpgh** [comment]
By definition I assume the targets are outside HCZ. Perhaps it wouldnt hurt mentioning it again as part of the text.

**Comment by KKruszynska** [comment]
I added this feature to MOP prod with this commit: 3fd5f63.

I forgot to add the comment about the HCZ. I will make a note to myself to add this when I push another change. For now: observe the new [Priority Targets view](https://mop.lco.global/prioritytargets/). Rows in beige are close to the predicted peak and targets in bold and underlined are currently observed.
