### ISSUE TITLE
MOP navbar image doesn't display in deployed MOP

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#204]
To customize the look 'n' feel of MOP, I added a background image to the navbar, which is included in the repo at [/static/tom_common/img/mop_navbar_grey_bkgd.png](https://github.com/LCOGT/mop/blob/master/static/tom_common/img/mop_navbar_grey_bkgd.png).  

While this displays just fine on my desktop's development install of MOP, it does not appear in either the dev or prod deployed versions. 

Investigating the reason for this absence using the browser's developer tools, I found the following error in the console:

```
A resource is blocked by OpaqueResponseBlocking, please check browser console for details. mop_navbar_grey_bkgd.png
```

Apparently this one image is falling foul of a browser security feature, though curiously all of the other images seem to appear, including images from the same static directory.  

While this isn't the most urgent issue right now, I figured I would document it for reference.

**Comment by rachel3834** [comment]
For context I added the image to the navbar in the [custom.css](https://github.com/LCOGT/mop/blob/master/static/tom_common/css/custom.css) definition:

```
.navbar {
  background-image: url("../img/mop_navbar_grey_bkgd.png");
  background-position: center;
  background-repeat: no-repeat;
  background-color: #000;
  color: #fff;
  height: 60px;
}
```

So my guess is that it's the relative path that's the problem here.

**Comment by rachel3834** [comment]
Reading through [this StackOverflow](https://stackoverflow.com/questions/5898776/how-to-refer-to-static-files-in-my-css-files) thread, this does seem to be the problem. 

Rather than use relative paths, the correct way to refer to a static path in the custom.css file is:

```
.navbar {
  background-image: url('/static/tom_common/img/mop_navbar_grey_bkgd.png');
  background-position: center;
  background-repeat: no-repeat;
  background-color: #000;
  color: #fff;
  height: 60px;
}
```

**Comment by jchate6** [comment]
@rachel3834 is this resolved?

**Comment by rachel3834** [comment]
No, not yet.  Using non-relative paths is the "approved Django Way" apparently, but this doesn't seem to play well for S3 deployments.  I found [this thread](https://forum.djangoproject.com/t/static-path-with-s3/28696/8) which was illuminating, but I am not keen to adjust the AWS storage config much.

**Comment by rachel3834** [comment]
To summarize everything so far, it's straight forward to refer to static files in HTML Django templates using the familiar syntax:
```
<nav class="navbar navbar-expand-md fixed-top" style="background: url('{% static 'tom_common/img/mop_navbar_grey_bkgd.png' %}')">
```

The template then handles sourcing the static file according to however this is configured in settings.py. 

But best practices for HTML/CSS design would argue that the background image for an element like this should be defined in the CSS file, and I can't seem to find a clean way to do that that works for an app deployed in AWS. 

@jchate6 This isn't urgent, but we should file this for TOM v3.0 under the UI/UX upgrade epic.  

For the time being, I've achieved the desired look for MOP's navbar by including some style tags in the template, so I'll close this issue.
