### ISSUE TITLE
Gaiaclassifier needs updating to PyLIMA=1.9

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#30]
The gaiaclassifier code is currently causes errors when it runs because it was written for the previous version of PyLIMA~0.8. 

The calls to the relevant model fitting routines need to be updated to those for PyLIMA=1.9.

**Comment by rachel3834** [comment]
The cronjob for this process calls the (gaia_classifier) [https://github.com/LCOGT/mop/blob/master/mop/management/commands/gaia_classifier.py] code, which is a management command on the MOP database.  

This in turn imports (fittools.py) [https://github.com/LCOGT/mop/blob/master/mop/toolbox/fittools.py] which was written for the old version of PyLIMA, so the calls to PyLIMA in the fitting processes need to be updated to PyLIMA v=1.9.

**Comment by ytsapras** [comment]
I had a look at this and started to modify it but Markus already alerted me he has already implemented some changes to fittools.py in his branch so we compared notes and the changes we implemented were very similar. We should discuss this during our next meeting.

**Comment by rachel3834** [comment]
@KKruszynska has fully revised this code, and introduced checks to evaluate the model fit and also crossmatch the targets against catalogs of known YSOs, QSOs, galaxies etc.  The revised code has been deployed in 4.1.12.
