### ISSUE TITLE
Prediction for intereferometry

### ISSUE THREAD

**Issue by ebachelet** [LCOGT/mop#34]
It is a long asked feature, adding predicted mags in infrared for potential trigger of interferometric observations. Code has been shared with @rachel3834 , we would need inputs from people to know what they really need

**Comment by rachel3834** [comment]
I've implemented all the functionality in the draft script provided by Etienne, and refactored it for easier integration. 
This includes querying the Gaia DR3 catalogue to fetch information on the target and neighbouring stars, estimating the J, H, K magnitudes of the lens star at event peak, and a decision making function that recommends whether or not each star would be a good interferometry target. 

Note that MOP does not currently use this recommendation to queue observations yet.  But I have added this evaluation to run_TAP so each target will be evaluated automatically, and a new tab to the Target Detail page to display the results.

**Comment by rachel3834** [comment]
Here is a preview of the new display for interferometry - feedback is welcome

![mop-dev-interfero-draft](https://github.com/LCOGT/mop/assets/10391660/b1acd85a-0d7d-4a60-8e3c-fbcd88ea3706)

**Comment by rachel3834** [comment]
One issue that has arisen in deployment is that the astroquery Vizier tool stores large temporary files following Gaia DR3 queries.  Turns out that when we run these queries for a large set of events, its possible to exceed the available space for temporary files in the pod.

**Comment by ebachelet** [comment]
I was about to suggest the row limit options of vizier but it seems implemented recently? Does that makes the trick? I think another way that might work is requesting a cut on Gaia magnitude, i.e. G<16 for example.

**Comment by rachel3834** [comment]
I implemented the row_limit option after I hit the memory issue but thanks for the idea of a magnitude cut, that makes sense too, and I'll add that.

**Comment by rachel3834** [comment]
Feedback from Arnaud indicates that querying the GSC catalog would be valuable, and he has provided a code segment which illustrates a function for selecting guide stars.  This will be the next phase of implementation, pending feedback from Arnaud to a few questions.

**Comment by rachel3834** [comment]
I've implemented the functionality from the code snippet provided by Arnaud.  MOP now queries the Guide Star Catalog and performs an evaluation of the nearby stars as candidates for Adaptive Optics and Fringe Tracking starss.  The results are now displayed as a colour-coded table under the interferometry tab for each target.  The Gaia catalog query results are still present, under a different tab for easy reference.

**Comment by rachel3834** [comment]
Arnaud used event OGLE-2023-BLG-1060 for testing purposes and noted that the table layout for the FTstrehl values in the AO/FT star matrix is broken when there are more than 1 AO stars.

**Comment by rachel3834** [comment]
I've fixed the table layout for the FTstrehl values in the star matrix and adjusted the colours.

**Comment by rachel3834** [comment]
Need to update the function used to select potential targets for interferometry, based on feedback from Arnaud:
H magnitude target around the peak (not only at peak, as we need an interval of time around the peak, to be defined), availability of AO and FT stars. If this is feasible, then we could simply add a keyword "GRAVITY" in the "Key" field on the left menu to filter potential targets (that we can then add by hand in the GRAVITY group).

**Comment by rachel3834** [comment]
Further feedback from Arnaud:
Regarding the K mags : an interesting option would be to quote the interval of time with the mag, independently of the peak mag used to flag the event. For example :

1) Flag with keyword "GRAVITY" if: K_Target < 14 and AO etc. and FT etc. : these events will appear if we set GRAVITY in the Filter on the left menu of MOP.

2) We add by hand interesting events in the "GRAVITY potential targets" grouping

3) In the Interferometry tab of the event, in the "Target Data" table, you could e.g. add  a new line with the following infos:

     Peak_K [mag]   |   Peak_date [y.m.d]  | Peak_date [JD-2450000]   |   Obs. interval [days]  
            12.45        |        2023-10-27        |         10244.95851            |       ± 4.56

**Comment by rachel3834** [comment]
I have implemented these requested features; requesting feedback from the team.

**Comment by rachel3834** [comment]
Etienne requested uncertainties on the predicted peak magnitudes in NIR bands to be propagated and displayed.

**Comment by rachel3834** [comment]
v4.1.8 deploys an upgrade to display the predicted peak magnitude uncertainties. To the best of my knowledge, this completes the functionality requested in this task.
