### ISSUE TITLE
Error retrieving ReducedDatums for OGLE-2023-BLG-256

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#45]
The harvest_ogle process fails with the error:

Traceback (most recent call last):
  File "/mop/./manage.py", line 21, in <module>
    main()
  File "/mop/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/mop/mop/management/commands/harvest_ogle.py", line 21, in handle
    Ogle.find_and_ingest_photometry(list_of_targets)
  File "/mop/mop/brokers/ogle.py", line 114, in find_and_ingest_photometry
    status = self.ingest_ogle_photometry(target, photometry)
  File "/mop/mop/brokers/ogle.py", line 148, in ingest_ogle_photometry
    rd, created = ReducedDatum.objects.get_or_create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 640, in get
    raise self.model.MultipleObjectsReturned(
tom_dataproducts.models.ReducedDatum.MultipleObjectsReturned: get() returned more than one ReducedDatum -- it returned 2!

**Comment by rachel3834** [comment]
Reopening this issue as the same situation now seems to be happening for event OGLE-2023-DG-0038.

**Comment by rachel3834** [comment]
I've adapted the OGLE data harvester so that I can now run it for a single event, and tested this on dev.  It ran just fine.

**Comment by rachel3834** [comment]
The same code now runs without error on prod as well.  I'm wondering if the process that ingests data for all events is running out of memory.

**Comment by rachel3834** [comment]
By monitoring the stern output at the command line, I found the following failure:

mop-harvestogle-28220785-4nwtd mop OGLE harvester: read and ingested photometry for event OGLE-2023-BLG-0761
mop-d77b75fb5-lc9vj mop 10.100.15.164 - - [28/Aug/2023:20:24:06 +0000] "GET / HTTP/1.1" 200 4824 "-" "kube-probe/1.22+"
mop-d77b75fb5-lc9vj mop 10.100.15.164 - - [28/Aug/2023:20:24:06 +0000] "GET / HTTP/1.1" 200 4824 "-" "kube-probe/1.22+"
mop-fitneedevents-28220880-r9mbz mop Target post save hook: Gaia22btt created: False
mop-fitneedevents-28220880-r9mbz mop Fitting event: Gaia22btt
mop-fitneedevents-28220880-r9mbz mop FIT: Found 2 photometry datapoints to model for event Gaia22btt
mop-fitneedevents-28220880-r9mbz mop Job failed: Gaia22btt
mop-fitneedevents-28220880-r9mbz mop Target(s) remaining in processing queue: 1964
mop-fitneedevents-28220880-r9mbz mop Target post save hook: Gaia22bts created: False
mop-fitneedevents-28220880-r9mbz mop Fitting event: Gaia22bts
mop-fitneedevents-28220880-r9mbz mop FIT: Found 2 photometry datapoints to model for event Gaia22bts
mop-fitneedevents-28220880-r9mbz mop Job failed: Gaia22bts
mop-fitneedevents-28220880-r9mbz mop Target(s) remaining in processing queue: 1965
mop-harvestogle-28220785-4nwtd mop Traceback (most recent call last):
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
mop-harvestogle-28220785-4nwtd mop     return self.get(**kwargs), False
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
mop-harvestogle-28220785-4nwtd mop     raise self.model.DoesNotExist(
mop-harvestogle-28220785-4nwtd mop tom_dataproducts.models.ReducedDatum.DoesNotExist: ReducedDatum matching query does not exist.
mop-harvestogle-28220785-4nwtd mop 
mop-harvestogle-28220785-4nwtd mop During handling of the above exception, another exception occurred:
mop-harvestogle-28220785-4nwtd mop 
mop-harvestogle-28220785-4nwtd mop Traceback (most recent call last):
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
mop-harvestogle-28220785-4nwtd mop     return self.cursor.execute(sql, params)
mop-harvestogle-28220785-4nwtd mop psycopg2.OperationalError: server closed the connection unexpectedly
mop-harvestogle-28220785-4nwtd mop 	This probably means the server terminated abnormally
mop-harvestogle-28220785-4nwtd mop 	before or while processing the request.
mop-harvestogle-28220785-4nwtd mop 
mop-harvestogle-28220785-4nwtd mop 
mop-harvestogle-28220785-4nwtd mop The above exception was the direct cause of the following exception:
mop-harvestogle-28220785-4nwtd mop 
mop-harvestogle-28220785-4nwtd mop Traceback (most recent call last):
mop-harvestogle-28220785-4nwtd mop   File "/mop/manage.py", line 21, in <module>
mop-harvestogle-28220785-4nwtd mop     main()
mop-harvestogle-28220785-4nwtd mop   File "/mop/manage.py", line 17, in main
mop-harvestogle-28220785-4nwtd mop     execute_from_command_line(sys.argv)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
mop-harvestogle-28220785-4nwtd mop     utility.execute()
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
mop-harvestogle-28220785-4nwtd mop     self.fetch_command(subcommand).run_from_argv(self.argv)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
mop-harvestogle-28220785-4nwtd mop     self.execute(*args, **cmd_options)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
mop-harvestogle-28220785-4nwtd mop     output = self.handle(*args, **options)
mop-harvestogle-28220785-4nwtd mop   File "/mop/mop/management/commands/harvest_ogle.py", line 22, in handle
mop-harvestogle-28220785-4nwtd mop     Ogle.find_and_ingest_photometry(list_of_targets)
mop-harvestogle-28220785-4nwtd mop   File "/mop/mop/brokers/ogle.py", line 122, in find_and_ingest_photometry
mop-harvestogle-28220785-4nwtd mop     status = self.ingest_ogle_photometry(target, photometry)
mop-harvestogle-28220785-4nwtd mop   File "/mop/mop/brokers/ogle.py", line 156, in ingest_ogle_photometry
mop-harvestogle-28220785-4nwtd mop     rd, created = ReducedDatum.objects.get_or_create(
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
mop-harvestogle-28220785-4nwtd mop     return getattr(self.get_queryset(), name)(*args, **kwargs)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 923, in get_or_create
mop-harvestogle-28220785-4nwtd mop     return self.create(**params), True
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 658, in create
mop-harvestogle-28220785-4nwtd mop     obj.save(force_insert=True, using=self.db)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/tom_dataproducts/models.py", line 354, in save
mop-harvestogle-28220785-4nwtd mop     return super().save()
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
mop-harvestogle-28220785-4nwtd mop     self.save_base(
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
mop-harvestogle-28220785-4nwtd mop     updated = self._save_table(
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
mop-harvestogle-28220785-4nwtd mop     results = self._do_insert(
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
mop-harvestogle-28220785-4nwtd mop     return manager._insert(
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
mop-harvestogle-28220785-4nwtd mop     return getattr(self.get_queryset(), name)(*args, **kwargs)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
mop-harvestogle-28220785-4nwtd mop     return query.get_compiler(using=using).execute_sql(returning_fields)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
mop-harvestogle-28220785-4nwtd mop     cursor.execute(sql, params)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
mop-harvestogle-28220785-4nwtd mop     return self._execute_with_wrappers(
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
mop-harvestogle-28220785-4nwtd mop     return executor(sql, params, many, context)
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
mop-harvestogle-28220785-4nwtd mop     with self.db.wrap_database_errors:
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
mop-harvestogle-28220785-4nwtd mop     raise dj_exc_value.with_traceback(traceback) from exc_value
mop-harvestogle-28220785-4nwtd mop   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
mop-harvestogle-28220785-4nwtd mop     return self.cursor.execute(sql, params)
mop-harvestogle-28220785-4nwtd mop django.db.utils.OperationalError: server closed the connection unexpectedly
mop-harvestogle-28220785-4nwtd mop 	This probably means the server terminated abnormally
mop-harvestogle-28220785-4nwtd mop 	before or while processing the request.
mop-harvestogle-28220785-4nwtd mop 
mop-fitneedevents-28220880-r9mbz mop Target post save hook: Gaia22btr created: False
mop-fitneedevents-28220880-r9mbz mop Fitting event: Gaia22btr
mop-fitneedevents-28220880-r9mbz mop FIT: Found 2 photometry datapoints to model for event Gaia22btr
mop-fitneedevents-28220880-r9mbz mop Job failed: Gaia22btr
mop-fitneedevents-28220880-r9mbz mop Target(s) remaining in processing queue: 1966
- mop-harvestogle-28220785-4nwtd › mop
mop-d77b75fb5

**Comment by rachel3834** [comment]
The above error occurred for event OGLE-2023-BLG-0762

**Comment by rachel3834** [comment]
This could be due to a timeout on the harvester process - Kubernetes is configured to kill pods after 4 hours-10min, and the process had been running that long.  It immediately restarted as designed, but the process automatically starts at event 1. This means the process will essentially never complete.

**Comment by ebachelet** [comment]
Actually it should complete. As the photometry is ingested only if not already there (I believe). This is how it works for MOA broker too. So iti should catch up at some points. Another way is to randomize the event number treated

**Comment by rachel3834** [comment]
That is true but I don't think this is actually an issue with get_or_creating a ReducedDatum.  I think we are seeing this failure because the pod is being torn down prematurely, while the process is running - hence the server errors. 

I did think about randomizing the ingest but I think for now I will go with reversing the order of the events, so that the latest events are ingested first.

**Comment by rachel3834** [comment]
After testing both a reverse sort function and a randomizer, I've opted for a compromise.  The harvester can now be configured to harvest one of a) a named specific target, b) all targets or c) given an integer number of targets to ingest data for.  

If the code is run in mode b it will reverse-sort the list of targets and ingest data for the most recent events first.  If given option c then it will select a random sample of the integer number of targets and ingest the data for those only.  I am combining this with an edit to the cronjob config to run the harvester in this mode every 2hrs, which will hopefully mean that it can catch up with ingesting data for a lot of targets relatively quickly, while not require a single pod to run for multiple hours.

**Comment by rachel3834** [comment]
Closing this issue as the harvester appears to be running as expected.
