### ISSUE TITLE
Problem with the command python manage.py harvest_gaia

### ISSUE THREAD

**Issue by ytsapras** [LCOGT/mop#55]
When executing `python manage.py harvest_gaia`, it fails with the following error message:

> tom_targets.TargetName: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
> 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TomTargetsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
> Traceback (most recent call last):
>   File "/home/mop/manage.py", line 21, in <module>
>     main()
>   File "/home/mop/manage.py", line 17, in main
>     execute_from_command_line(sys.argv)
>   File "/home/anaconda3/envs/mop_venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
>     utility.execute()
>   File "/home/anaconda3/envs/mop_venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/anaconda3/envs/mop_venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/anaconda3/envs/mop_venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
>     output = self.handle(*args, **options)
>   File "/home/mop/mop/management/commands/harvest_gaia.py", line 100, in handle
>     clean_alert = Gaia.to_generic_alert(alert)
>   File "/home/anaconda3/envs/mop_venv/lib/python3.10/site-packages/tom_alerts/brokers/gaia.py", line 125, in to_generic_alert
>     timestamp = parse(alert['obstime'])
> TypeError: 'list_iterator' object is not subscriptable

**Comment by rachel3834** [comment]
This issue was traced to the TOM's Gaia alert broker, which was recently updated.  The error was caused because the broker now returns an additional variable from the alert ingest function which was not being handled in our code. This issue was fixed in v.4.0.5.8.
