### ISSUE TITLE
Sky_location flag is sometimes set to "Unknown"

### ISSUE THREAD

**Issue by KKruszynska** [LCOGT/mop#68]
For some targets in MOP, Sky_location flag is set to "Unknown" instead of "In HCZ" / "Outside of HCZ". This means the sky location evaluation should take place in a different place in MOP. This flag still needs to be recorded, because it's used by TAP to evaluate targets for follow-up.

Examples:
https://mop.lco.global/targets/36522/
https://mop.lco.global/targets/36484/
https://mop.lco.global/targets/36481/

**Comment by rachel3834** [comment]
I've implemented a function to set this sky_location flag for all events on ingest in the broker harvesters and also in the TargetDetail view, so it should now always be set.  Will deploy this fix as soon as Jenkins is ready.
