### ISSUE TITLE
Model fits peak in spike or data gap

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#69]
A number of the microlensing models fitted for various events appear to poorly fit the data, with the peak of the event falling in a data gap, or not fitting the data.  

Example is OGLE-2023-BLG-1262

![newplot(1)](https://github.com/LCOGT/mop/assets/10391660/1587ce65-775f-4413-bd42-31dbd8d2c82c)

**Comment by rachel3834** [comment]
Both mop-dev and mop-prod give the same results.  Interestingly, when testing on local host, a fit to OGLE data only produced a sensible response. 

![newplot(2)](https://github.com/LCOGT/mop/assets/10391660/a638e883-8222-4f28-8f9e-2fce21f34a57)

However, when the ZTF data were included, I get the same spurious peak as seen in the prod and dev servers:

![newplot(3)](https://github.com/LCOGT/mop/assets/10391660/8df534a1-5c21-4ed2-88a8-a43b4a93bfd1)

**Comment by rachel3834** [comment]
Previously, odd fitting behavior has been tracked to poorly-chosen initial guess values, which related to the input lightcurve arrays not being in time-order.  So firstly I checked to make sure that this is not the same fault reoccuring. 

Printing out the arrays, they are correctly in time-stamp order.  However I noticed that the OGLE lightcurve actually starts **after** the two ZTF lightcurves.  This is unusual in the Bulge, but can happen as a result of OGLE expanding their survey region following the pandemic break.  

First timestamps in the lightcurves:
ZTF_g : 2458246.96
ZTF_r : 2458220.01
OGLE_I : 2458272.79

**Comment by rachel3834** [comment]
This may matter when it comes to estimating initial-guess values for the model fit.  MOP enforces an order of preference when it creates the Telescope objects associated with the event, which doesn't matter for the actual fit but may for the initial guess function.  The ordering favors OGLE first, followed by ZTF data.  

To test this, I forced MOP to change the ordering and compared the values of the initial-guess t0 produced. 

Test 1) OGLE data only: t0(guess) = 2460217.  Resulting model fit is good
Test 2) ZTF data (r and g) only: t0(guess) = 2458401.  Resulting model fits to a spurious peak in the r-band lightcurve, which is first in the ordering of the datasets.  This is reasonable, since the ZTF data do not include the event in this case. 
Test 3) OGLE + ZTF (r+g), OGLE data first: t0(guess) = 2459819.  Resulting model fits a non-existent peak in a data gap in the lightcurve. 
Test 4) OGLE + ZTF (r+g), ZTF data first: t0(guess) = 2459819.  Resulting model fits a non-existent peak in a data gap in the lightcurve. 

Comparing the results for tests 3 and 4, it appears as though the ordering of the datasets in the fitting array does not have much of an impact.  However, the only lightcurve that includes the microlensing event is the OGLE lightcurve, does not have the earliest baseline timestamp.

**Comment by rachel3834** [comment]
My hypothesis now is that the lightcurve which dominates the model fit for the event (necessarily OGLE since the ZTF data don't include the event), needs to have the earliest timestamp for the initial guess function to use it to guess a value for t0. 

To test this, I artifically restricted the ZTF datapoints, while leaving the OGLE lightcurve untouched.  I included ZTF data in the fit only if the timestamp > 246000.0, i.e. after the first datapoint in the OGLE lightcurve.  

This produced an initial guess t0 = 2460190.510030876, and a sensible model fit.

**Comment by rachel3834** [comment]
These results are consistent, even if the (truncated) ZTF data is given priority in the ordering of the datasets

![newplot(4)](https://github.com/LCOGT/mop/assets/10391660/5f77b6ed-45e6-4113-a029-e8618e9cd684)

**Comment by ebachelet** [comment]
I think I know what is going on. Gradient method guess in pyLIMA (TRF and LM) have a method to find t0 for each datasets. It then use a median of these values. It is implictly expected that each dataset contain some microlensing signal. Of course, if there is not, the algorithm will find a wrong t0. For the case just above, it implicates that the only good guess will be for OGLE, as ZTF does not observe the peak. Therefore, t0 will be wrong and most liely the fit will fail.

**Comment by rachel3834** [comment]
So this appears to be a corner case in the initial-guess function in the instance where the lightcurve with the most data on the event doesn't have the longest baseline.  Unfortunately, we may be encountering these circumstances a lot this season, due to OGLE restarting observations and including new fields.

**Comment by rachel3834** [comment]
I believe this issue was resolved by revising run_TAP's fitting logic and fixing bugs and by the latest update to PyLIMA
