### ISSUE TITLE
PyLIMA eliminating all data during modeling?

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#86]
Running fitneedevents, I am seeing a lot of instances of the following error.  [MOA-2023-BLG-0072](https://mop.lco.global/targets/29310/) is one example of this issue where there is a (admittedly noisy) lightcurve which nevertheless includes a clear microlensing event which was previously fitted.  

Fitting event: MOA-2023-BLG-072
FIT: Found 2 datasets and a total of 7074 datapoints to model for event MOA-2023-BLG-072
FITTOOLS: established event
pyLIMA found (and eliminate) some bad_data for telescope Tel_1, please check your_telescope.bad_data
FITTOOLS: appended 2 telescopes
ERROR : There is no associated lightcurve in magnitude or flux with this telescopes : Tel_1, add one with telescope.lightcurve = your_data
Job failed: MOA-2023-BLG-072

**Comment by ebachelet** [comment]
I see this event fitted recently, is it fixed? Btw I see two tags for last fit now , maybe we should get rid of one?

**Comment by rachel3834** [comment]
Thanks for pointing that out.  I've removed the extra tag, since the last
fit parameter is now populated programmatically.

**Comment by rachel3834** [comment]
I'm still seeing the following sequence of output for lots of events:

mop-fitneedevents-28314240-5dvmf mop Fitting event: OGLE-2023-BLG-0760
mop-fitneedevents-28314240-5dvmf mop FIT: Found 2 datasets and a total of 2682 datapoints to model for event OGLE-2023-BLG-0760
mop-fitneedevents-28314240-5dvmf mop FITTOOLS: established event
mop-fitneedevents-28314240-9gw6v mop Target post save hook: OGLE-2023-DG-0034 created: False
mop-fitneedevents-28314240-5dvmf mop pyLIMA found (and eliminate) some bad_data for telescope Tel_1, please check your_telescope.bad_data
mop-fitneedevents-28314240-5dvmf mop FITTOOLS: appended 2 telescopes
mop-fitneedevents-28314240-5dvmf mop ERROR : There is no associated lightcurve in magnitude or flux with this telescopes : Tel_1, add one with telescope.lightcurve = your_data
mop-fitneedevents-28314240-5dvmf mop Job failed: OGLE-2023-BLG-0760

Currently this results in MOP having no model at all, which is an issue with the exception handling, but I am more concerned that the data filtering is excessive.

**Comment by ebachelet** [comment]
In principle, pyLIMA now just eliminate duplicate in time and non-finite row for a datasets. As said here, it seems he has found such in the event 0034. One can have a look at those in the Tel_1.bad_data

**Comment by rachel3834** [comment]
Monitoring this in operation, I don't think this function is being overzealous; we seem to be getting reasonable fits, so closing this issue for now.
