### ISSUE TITLE
runTAP returning wrong observation mode

### ISSUE THREAD

**Issue by ebachelet** [LCOGT/mop#92]

**Comment by rachel3834** [comment]
Although runTAP has been switched to "live_obs" mode for OGLE targets, it is still not recommending observations for suitable targets, even those that have high TAP_priority or TAP_priority_longtE. 

Example log output from runTAP for OGLE-2023-BLG-1262 (currently a high priority):

runTAP: Started with options {'verbosity': 1, 'settings': None, 'pythonpath': None, 'traceback': False, 'no_color': False, 'force_color': False, 'skip_checks': False, 'target_name': 'OGLE-2023-BLG-1262', 'observe': 'live_obs'}
runTAP: Loaded event OGLE-2023-BLG-1262
runTAP: analyzing event OGLE-2023-BLG-1262
TAP model parameters sanity check returned True
Target post save hook: OGLE-2023-BLG-1262 created: False
runTAP: Planet priority: 8.44418972561765, 1.837421671979953
runTAP: Last datapoint: 2460245.5321602304
runTAP: Long tE priority: 8.625156110333892 0.34082125729217977
Target post save hook: OGLE-2023-BLG-1262 created: False
/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning:

DateTimeField ReducedDatum.timestamp received a naive datetime (2023-11-02 21:11:22.307506) while time zone support is active.

/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning:

DateTimeField ReducedDatum.timestamp received a naive datetime (2023-11-02 21:11:22.317075) while time zone support is active.

runTAP: Event NOT in OMEGA: False
runTAP: Event alive? True
runTAP: Event should be observed
runTAP: Event visible?  True
runTAP: Mag now = 16.46272628039737
runTAP: mag_baseline: 16.857
runTAP: Observing mode: OGLE-2023-BLG-1262 None
Target post save hook: OGLE-2023-BLG-1262 created: False
INTERFERO: Evaluating event OGLE-2023-BLG-1262
INTERFERO: Identified 1 stars in the neighbourhood of OGLE-2023-BLG-1262
INTERFERO: Calculated uncertainties Gmag=15.890214+/-0.3658962227948249mag
INTERFERO: Computed JHK photometry for neighbouring stars
/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning:

DateTimeField ReducedDatum.timestamp received a naive datetime (2018-06-29 08:15:27.243860) while time zone support is active.

INTERFERO: Evaluation for interferometry for OGLE-2023-BLG-1262: No guide=0
Target post save hook: OGLE-2023-BLG-1262 created: False
INTERFERO: Stored neighbouring star data in MOP
INTERFERO: Querying GSC catalog around event OGLE-2023-BLG-1262
INTERFERO: Compose matrix of AO and FT stars for OGLE-2023-BLG-1262
INTERFERO: Stored GSC search results in MOP
INTERFERO: Stored AOFT matrix in MOP
runTAP: Evaluated OGLE-2023-BLG-1262 for interferometry

**Comment by rachel3834** [comment]
Reviewing this log output this line:

> runTAP: Observing mode: OGLE-2023-BLG-1262 None

suggests that function TAP.TAP_observing_mode is not classifying this event in one of our target-selection categories.  
Since we manually decided to select it, the output from this function needs to be tested using this target as a case study. 

For reference, no target has been recommended for observation by TAP yet, suggesting that the criteria are too conservative.

**Comment by KKruszynska** [comment]
I ran a test for events that should be selected.

1. Planet priority events
These could be selected, but the difference between current magnitude and baseline magnitude is smaller than 2 mags. We can loosen this criterium and demand only a 1mag difference.
```
OGLE-2023-BLG-1322: pri=16.979 +/- 5.422, magnow=16.753, base=17.293, diff = 0.540
OGLE-2023-BLG-1267: pri=119.812 +/- 4.395, magnow=16.871, base=16.948, diff = 0.077
OGLE-2023-BLG-1262: pri=10.467 +/- 1.216, magnow=15.707, base=16.856, diff = 1.149
```

2. Long event priority
Events that could match the criteria, have baselines below 17.5 mags. Except one:
OGLE-2023-BLG-1267 base_mag: 16.948 priority_long_event:  353.94301 t_E :  2999.99933 +/- 0.14042 red_chi2:  1.922
This one has wrong timescale, but the error on it is small.
@rachel3834 could you check the logs or the listed events?

I'm trying to understand why I see different values for some priorities when taking them from MOP and calculating them offline.

**Comment by rachel3834** [comment]
Looking at OGLE-2023-BLG-1267, the model fitted has a very bright blend magnitude so this tE is not to be trusted I think.

**Comment by rachel3834** [comment]
Here's the runTAP output for all of those events:
OGLE-2023-BLG-1267
=================

runTAP: Started with options {'verbosity': 1, 'settings': None, 'pythonpath': None, 'traceback': False, 'no_color': False, 'force_color': False, 'skip_checks': False, 'target_name': 'OGLE-2023-BLG-1267', 'observe': 'live_obs'}
runTAP: Loaded event OGLE-2023-BLG-1267
runTAP: analyzing event OGLE-2023-BLG-1267
TAP model parameters sanity check returned True
Target post save hook: OGLE-2023-BLG-1267 created: False
runTAP: Planet priority: 119.5313985319878, 4.376680673783773
runTAP: Last datapoint: 2460236.2614544323
runTAP: Long tE priority: 398.5546668351709 0.001872284769413504
Target post save hook: OGLE-2023-BLG-1267 created: False
/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning:

DateTimeField ReducedDatum.timestamp received a naive datetime (2023-11-03 00:00:51.837624) while time zone support is active.

/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning:

DateTimeField ReducedDatum.timestamp received a naive datetime (2023-11-03 00:00:51.850933) while time zone support is active.

runTAP: Event NOT in OMEGA: False
runTAP: Event alive? True
runTAP: Event should be observed
runTAP: Event visible?  True
runTAP: Mag now = 16.872136437616337
runTAP: mag_baseline: 16.948
runTAP: Observing mode: OGLE-2023-BLG-1267 priority_long_event
Target post save hook: OGLE-2023-BLG-1267 created: False
runTAP: Determined observation configurations: [{'observation_mode': 'NORMAL', 'operator': 'SINGLE', 'instrument_type': '1M0-SCICAM-SINISTRO', 'telescope_class': '1m0', 'proposal': 'KEY2023B-004', 'facility': 'LCO', 'max_airmass': 2.0, 'min_lunar_distance': 15.0, 'max_lunar_phase': 1.0, 'target': <Target: OGLE-2023-BLG-1267>, 'filters': ['SDSS-i'], 'ipp': 1.05, 'group_id': 'OGLE-2023-BLG-1267_reg_phot_ip', 'period': 48.0, 'jitter': 48.0, 'exposure_times': [271.9], 'exposure_counts': [1], 'tstart': datetime.datetime(2023, 11, 3, 0, 0, 52, 949988), 'tend': datetime.datetime(2023, 11, 10, 0, 0, 52, 949991)}, {'observation_mode': 'NORMAL', 'operator': 'SINGLE', 'instrument_type': '1M0-SCICAM-SINISTRO', 'telescope_class': '1m0', 'proposal': 'KEY2023B-004', 'facility': 'LCO', 'max_airmass': 2.0, 'min_lunar_distance': 15.0, 'max_lunar_phase': 1.0, 'target': <Target: OGLE-2023-BLG-1267>, 'filters': ['SDSS-g', 'SDSS-i'], 'ipp': 1.0, 'group_id': 'OGLE-2023-BLG-1267_reg_phot_gpip', 'period': 168.0, 'jitter': 168.0, 'exposure_times': [600.0, 271.9], 'exposure_counts': [1, 1], 'tstart': datetime.datetime(2023, 11, 3, 0, 0, 52, 950000), 'tend': datetime.datetime(2023, 11, 10, 0, 0, 52, 950001)}]
runTAP: Filtered out duplicates: []
runTAP: Build observation requests: []
runTAP: SUBMITTING OBSERVATIONS
INTERFERO: Evaluating event OGLE-2023-BLG-1267
INTERFERO: Identified 4 stars in the neighbourhood of OGLE-2023-BLG-1267
INTERFERO: Calculated uncertainties Gmag=15.7634+/-0.2416854377711451mag
INTERFERO: Computed JHK photometry for neighbouring stars
/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning:

DateTimeField ReducedDatum.timestamp received a naive datetime (2018-06-29 08:15:27.243860) while time zone support is active.

INTERFERO: Evaluation for interferometry for OGLE-2023-BLG-1267: No guide=0
Target post save hook: OGLE-2023-BLG-1267 created: False
INTERFERO: Stored neighbouring star data in MOP
INTERFERO: Querying GSC catalog around event OGLE-2023-BLG-1267
INTERFERO: Compose matrix of AO and FT stars for OGLE-2023-BLG-1267
INTERFERO: Stored GSC search results in MOP
INTERFERO: Stored AOFT matrix in MOP
Target post save hook: OGLE-2023-BLG-1267 created: False
runTAP: Evaluated OGLE-2023-BLG-1267 for interferometry


=> In this case it looks like runTAP did try to submit observations but thought it had a duplicate instance, so did not ultimately submit.  That's a separate issue to the priorities.

**Comment by rachel3834** [comment]
The others I've not yet been able to runTAP since it is currently running under the cron.

**Comment by ebachelet** [comment]
OGLE-2023-BLG-1267 look anomalous btw, so not sure if this is a good target to play with
https://ogle.astrouw.edu.pl/ogle4/ews/blg-1267.html

**Comment by rachel3834** [comment]
This seems to have been caused by running separate instances of runTAP on mop-dev and mop-prod, leading to confusion.  See Issue #97
