### ISSUE TITLE
runTAP filtering too many obs out of the requested list as duplicates

### ISSUE THREAD

**Issue by rachel3834** [LCOGT/mop#93]
See issue #92 
Example for OGLE-2023-BLG-1267, runTAP recommended observations and constructed a list of requests but then filtered them all out.  Manual inspection of the LCO portal shows no PENDING observations for this target but some with status COMPLETED.

**Comment by KKruszynska** [comment]
This is surprising. Let me know if I can be any help with this.

**Comment by rachel3834** [comment]
This issue was traced to the function in obs_control that reviewed the list of PENDING requests retrieved from the LCO portal.  I have refactored this function to make it a bit more efficient - rather than querying the portal (an external service) for every target, MOP now queries it once for all targets, then parses the results into a dictionary which is more easily checked.  
This was deployed into operation with release 4.1.11 and appears to be working.
